const { test } = require("node:test");
const assert = require("node:assert/strict");
const { EventEmitter } = require("node:events");
const fs = require("node:fs/promises");
const os = require("node:os");
const path = require("node:path");
const { createHash } = require("node:crypto");
const YAML = require("yaml");
const { execFile } = require("node:child_process");
const { promisify } = require("node:util");
const { UpdateManager } = require("../src/update-manager.cjs");
const { MacUpdater, parseManifest, acknowledgeMacUpdate } = require("../src/mac-updater.cjs");
const feed = `https://updates.example/desktop-updates/darwin/${process.arch}/`;
const bytes = Buffer.from("a complete update archive");
const manifest = { version: "0.0.2", files: [{ url: `Plasmic-0.0.2-mac-${process.arch}.zip`, size: bytes.length, sha512: createHash("sha512").update(bytes).digest("base64") }] };
function manager(updater, beforeInstall = async () => {}) {
  return new UpdateManager({ updater, version: "0.0.1", enabled: true, beforeInstall });
}
test("checks download automatically but installation waits for confirmation and saves before quitting", async () => {
  const updater = new EventEmitter();
  const order = [];
  updater.checkForUpdates = async () => { updater.emit("checking-for-update"); updater.emit("update-available", manifest); };
  updater.downloadUpdate = async () => { updater.emit("download-progress", { percent: 45.3 }); updater.emit("update-downloaded", manifest); };
  updater.quitAndInstall = async () => order.push("install");
  const updates = manager(updater, async () => order.push("save"));
  const phases = [];
  updates.on("status", ({ phase }) => phases.push(phase));
  assert.equal(updater.autoDownload, false);
  assert.equal(updater.autoInstallOnAppQuit, false);
  assert.equal((await updates.command("install")).phase, "idle");
  assert.equal((await updates.command("check")).phase, "downloaded");
  assert.deepEqual(phases, ["checking", "available", "downloading", "downloading", "downloaded"]);
  assert.equal((await updates.command("check")).phase, "downloaded");
  assert.deepEqual(order, []);
  await updates.command("install");
  assert.deepEqual(order, ["save", "install"]);
});
test("failed save blocks installation and supports retry without another download", async () => {
  const updater = new EventEmitter();
  let installs = 0, saves = 0;
  updater.quitAndInstall = () => installs++;
  const updates = manager(updater, async () => { if (++saves === 1) throw new Error("Save failed"); });
  updater.emit("update-downloaded", manifest);
  assert.equal((await updates.command("install")).retry, "install");
  assert.equal(installs, 0);
  await updates.command("install");
  assert.equal(installs, 1);
});
test("overlapping checks share one request; failed downloads retry the same version", async () => {
  const updater = new EventEmitter();
  let resolve, checks = 0, downloads = 0;
  updater.checkForUpdates = () => { checks++; return new Promise((done) => { resolve = done; }); };
  updater.downloadUpdate = async () => { if (++downloads === 1) throw new Error("Network offline"); updater.emit("update-downloaded", manifest); };
  const updates = manager(updater);
  const first = updates.command("check"), second = updates.command("check");
  assert.equal(checks, 1);
  updater.emit("update-available", manifest);
  resolve();
  const results = await Promise.all([first, second]);
  assert.equal(results[0].retry, "download");
  assert.equal(results[1].retry, "download");
  assert.equal(downloads, 1);
  assert.equal((await updates.command("download")).phase, "downloaded");
});
test("startup downloads in the background and periodic checks cannot interrupt the download or ready state", async (t) => {
  t.mock.timers.enable({ apis: ["setInterval"] });
  const updater = new EventEmitter();
  let checks = 0, downloads = 0, finish;
  updater.checkForUpdates = async () => { checks++; updater.emit("update-available", manifest); };
  updater.downloadUpdate = () => { downloads++; return new Promise((resolve) => { finish = () => { updater.emit("update-downloaded", manifest); resolve(); }; }); };
  const updates = manager(updater);
  t.after(() => updates.stop());
  updates.start();
  await new Promise((resolve) => setImmediate(resolve));
  assert.equal(updates.state.phase, "downloading");
  t.mock.timers.tick(10 * 60 * 1000);
  assert.equal(checks, 1);
  assert.equal(downloads, 1);
  finish();
  await updates.running;
  t.mock.timers.tick(10 * 60 * 1000);
  assert.equal(updates.state.phase, "downloaded");
  assert.equal(checks, 1);
});
test("stable version comparison rejects downgrade, prerelease, traversal and cross-origin artifacts", () => {
  assert.equal(parseManifest(YAML.stringify(manifest), "0.0.2", feed), null);
  assert.equal(parseManifest(YAML.stringify(manifest), "0.0.10", feed), null);
  assert.equal(parseManifest(YAML.stringify({ ...manifest, version: "0.0.10" }), "0.0.9", feed).version, "0.0.10");
  for (const url of ["../update.zip", "https://other.example/update.zip", "dir/update.zip"]) {
    assert.throws(() => parseManifest(YAML.stringify({ ...manifest, files: [{ ...manifest.files[0], url }] }), "0.0.1", feed), /artifact/);
  }
  assert.throws(() => parseManifest(YAML.stringify({ ...manifest, version: "0.0.3-beta.1" }), "0.0.1", feed), /stable/);
});
test("macOS downloads verify complete bytes and SHA-512 before reporting ready; failed downloads remove partial files", async (t) => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "plasmic-updates-"));
  t.after(() => fs.rm(root, { recursive: true, force: true }));
  let corrupt = false, downloaded = 0;
  const updater = new MacUpdater({ app: { getPath: () => root, getVersion: () => "0.0.1" }, feedUrl: feed, fetch: async (url) => url.endsWith(".yml") ? new Response(YAML.stringify(manifest)) : new Response(corrupt ? Buffer.from("bad") : bytes) });
  updater.on("update-downloaded", () => downloaded++);
  await updater.checkForUpdates();
  const [file] = await updater.downloadUpdate();
  assert.deepEqual(await fs.readFile(file), bytes);
  assert.equal(downloaded, 1);
  corrupt = true;
  await assert.rejects(updater.downloadUpdate(), /checksum/);
  assert.equal(downloaded, 1);
  await assert.rejects(fs.stat(file + ".partial"), { code: "ENOENT" });
  const malicious = new MacUpdater({ app: { getPath: () => root, getVersion: () => "0.0.1" }, feedUrl: feed, fetch: async () => new Response(bytes, { status: 503 }) });
  await assert.rejects(malicious.checkForUpdates(), /503/);
});
test("only the expected installed version and bundle acknowledge an update", async (t) => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "plasmic-update-receipt-"));
  t.after(() => fs.rm(root, { recursive: true, force: true }));
  await fs.mkdir(path.join(root, "updates"));
  const id = "eb954cc1-07c2-4b0b-85a0-5d00eedf12ae";
  const target = path.join(root, "Plasmic.app");
  const transaction = { id, version: "0.0.2", target };
  await fs.writeFile(path.join(root, "updates/mac-transaction.json"), JSON.stringify(transaction));
  const app = { getPath: () => root, getVersion: () => "0.0.1", getAppPath: () => path.join(target, "Contents/Resources/app.asar") };
  await acknowledgeMacUpdate(app);
  await assert.rejects(fs.stat(path.join(root, `updates/${id}.ready`)), { code: "ENOENT" });
  app.getVersion = () => "0.0.2";
  await fs.writeFile(path.join(root, "updates/Plasmic-0.0.2.zip"), "cached");
  await fs.mkdir(path.join(root, "updates/extract-fixture"));
  await fs.writeFile(path.join(root, "updates/extract-fixture/data"), "extracted");
  await acknowledgeMacUpdate(app);
  assert.equal(await fs.readFile(path.join(root, `updates/${id}.ready`), "utf8"), "ready");
  await assert.rejects(fs.stat(path.join(root, "updates/Plasmic-0.0.2.zip")), { code: "ENOENT" });
  await assert.rejects(fs.stat(path.join(root, "updates/extract-fixture")), { code: "ENOENT" });
});
test("development and unpacked launches keep updates disabled even after an updater error", async () => {
  const updater = new EventEmitter();
  updater.checkForUpdates = updater.downloadUpdate = updater.quitAndInstall = () => { throw new Error("Updater must not run"); };
  const updates = new UpdateManager({ updater, enabled: false, version: "0.0.1", beforeInstall: async () => { throw new Error("Must not install"); } });
  updater.emit("error", new Error("Prior install failed"));
  for (const command of ["check", "download", "install"]) assert.equal((await updates.command(command)).phase, "disabled");
});
test("installed clients check immediately at startup and every ten minutes until stopped", async (t) => {
  t.mock.timers.enable({ apis: ["setInterval"] });
  const updater = new EventEmitter();
  let checks = 0;
  updater.checkForUpdates = async () => { checks++; updater.emit("update-not-available"); };
  const updates = manager(updater);
  t.after(() => updates.stop());
  updates.start();
  assert.equal(checks, 1);
  await updates.running;
  t.mock.timers.tick(10 * 60 * 1000 - 1);
  assert.equal(checks, 1);
  t.mock.timers.tick(1);
  await updates.running;
  assert.equal(checks, 2);
  t.mock.timers.tick(10 * 60 * 1000);
  await updates.running;
  assert.equal(checks, 3);
  updates.stop();
  t.mock.timers.tick(10 * 60 * 1000);
  assert.equal(checks, 3);
});
test("release validation refuses incomplete or modified artifacts before NAS upload", async (t) => {
  const { validateRelease } = await import("../scripts/release-artifacts.mjs");
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "plasmic-release-"));
  t.after(() => fs.rm(root, { recursive: true, force: true }));
  await fs.writeFile(path.join(root, "latest-mac.yml"), YAML.stringify(manifest));
  await fs.writeFile(path.join(root, manifest.files[0].url), bytes);
  assert.equal((await validateRelease(root, "darwin", "0.0.2")).files.length, 1);
  await fs.writeFile(path.join(root, manifest.files[0].url), "wrong bytes");
  await assert.rejects(validateRelease(root, "darwin", "0.0.2"), /checksum or size/);
  await assert.rejects(validateRelease(root, "darwin", "0.0.3"), /manifest version/);
});
test("macOS helper restores the previous bundle if the replacement cannot launch", { skip: process.platform !== "darwin" }, async (t) => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "plasmic-update-rollback-"));
  t.after(() => fs.rm(root, { recursive: true, force: true }));
  const target = path.join(root, "Plasmic.app"), staged = path.join(root, "staged.app"), backup = path.join(root, "backup.app");
  await fs.mkdir(target);
  await fs.mkdir(staged);
  await fs.writeFile(path.join(target, "old-version"), "retained");
  await assert.rejects(promisify(execFile)("/bin/sh", [path.resolve(__dirname, "../src/mac-update-install.sh"), "2147483647", target, staged, backup, path.join(root, "receipt"), path.join(root, "transaction"), path.join(root, "failure"), path.join(root, "log"), path.join(root, "pid")]));
  assert.equal(await fs.readFile(path.join(target, "old-version"), "utf8"), "retained");
  assert.match(await fs.readFile(path.join(root, "failure"), "utf8"), /previous version restored/);
  await assert.rejects(fs.stat(backup), { code: "ENOENT" });
});
