import { useI18n } from "@/wab/client/i18n";
// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import {
  DefaultSaveIndicatorProps,
  PlasmicSaveIndicator,
} from "@/wab/client/plasmic/plasmic_kit_top_bar/PlasmicSaveIndicator";
import { useStudioCtx } from "@/wab/client/studio-ctx/StudioCtx";
import { HTMLElementRefOf } from "@plasmicapp/react-web";
import { Tooltip } from "antd";
import { observer } from "mobx-react";
import * as React from "react";

export type SaveIndicatorProps = DefaultSaveIndicatorProps;

function SaveIndicator_(
  props: SaveIndicatorProps,
  ref: HTMLElementRefOf<"div">,
) {
  const { t } = useI18n();
  const studioCtx = useStudioCtx();
  const status = studioCtx.saveStatus;
  const labels = {
    saved: t("Saved"),
    pending: t("Pending changes"),
    saving: t("Saving…"),
    error: t("Save failed. Click to retry."),
    blocked: t("Saving blocked. Resolve the issue above."),
    unlogged: t("Unlogged changes"),
  };
  const canRetry = status === "error" && studioCtx.canSave();
  const retry = () => {
    if (canRetry) {
      void studioCtx.save();
    }
  };

  return (
    <Tooltip title={labels[status]}>
      <PlasmicSaveIndicator
        {...props}
        root={{
          ref,
          role: canRetry ? "button" : "status",
          "aria-label": labels[status],
          "aria-live": "polite",
          tabIndex: canRetry ? 0 : undefined,
          onClick: retry,
          onKeyDown: (event) => {
            if (canRetry && (event.key === "Enter" || event.key === " ")) {
              event.preventDefault();
              retry();
            }
          },
        }}
        freeBox={{
          style:
            status === "error" || status === "blocked"
              ? { backgroundColor: "#d92d20" }
              : undefined,
        }}
        saveState={
          status === "unlogged"
            ? "unlogged"
            : status !== "saved"
              ? "dirty"
              : undefined
        }
      />
    </Tooltip>
  );
}

const SaveIndicator = observer(React.forwardRef(SaveIndicator_));
export default SaveIndicator;
