// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import { useShareDialog } from "@/wab/client/components/top-bar/useShareDialog";
import { useI18n } from "@/wab/client/i18n";
import {
  DefaultShareButtonProps,
  PlasmicShareButton,
} from "@/wab/client/plasmic/plasmic_kit_top_bar/PlasmicShareButton";
import { observer } from "mobx-react";
import * as React from "react";

type ShareButtonProps = DefaultShareButtonProps;

const ShareButton = observer((props: ShareButtonProps) => {
  const { t: uiT } = useI18n();
  const { openShareDialog } = useShareDialog();

  return (
    <>
      <PlasmicShareButton
        {...props}
        onClick={() => openShareDialog()}
        share={{ "aria-label": uiT("Share project") }}
        tooltip={uiT("Share project")}
      />
    </>
  );
});

export default ShareButton;
