import { useI18n } from "@/wab/client/i18n";
import { UiText } from "@/wab/client/i18n/UiText";
// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.

import {
  MenuBuilder,
  TextAndShortcut,
} from "@/wab/client/components/menu-builder";
import { IFrameAwareDropdownMenu } from "@/wab/client/components/widgets";
import { Icon } from "@/wab/client/components/widgets/Icon";
import HidePlaceholderIcon from "@/wab/client/plasmic/plasmic_kit/PlasmicIcon__HidePlaceholder";
import ShowPlaceholderIcon from "@/wab/client/plasmic/plasmic_kit/PlasmicIcon__ShowPlaceholder";
import Refresh2SvgIcon from "@/wab/client/plasmic/plasmic_kit_icons/icons/PlasmicIcon__Refresh2Svg";
import {
  DefaultViewButtonProps,
  PlasmicViewButton,
} from "@/wab/client/plasmic/plasmic_kit_top_bar/PlasmicViewButton";
import { getComboForAction } from "@/wab/client/shortcuts/studio/studio-shortcuts";
import { useStudioCtx } from "@/wab/client/studio-ctx/StudioCtx";
import { isDedicatedArena } from "@/wab/shared/Arenas";
import { DEVFLAGS } from "@/wab/shared/devflags";
import { Menu, Tooltip } from "antd";
import { observer } from "mobx-react";
import { ok } from "neverthrow";
import * as React from "react";

type ViewButtonProps = DefaultViewButtonProps;

const contentCreatorModeHelp = (
  <>
    <div>
      <UiText
        message={
          "Content creator mode simplifies the UI and limits edits to ensure design consistency."
        }
      />
    </div>
    <div className="mt-sm">
      <UiText
        message={
          "It limits insertion to existing components in this project and hides style settings and most design panels."
        }
      />
    </div>
    <div className="mt-sm">
      <UiText
        message={
          "Users with content creator roles always use content creator mode."
        }
      />
    </div>
  </>
);

const ViewButton = observer(function ViewButton(props: ViewButtonProps) {
  const { t } = useI18n();
  const studioCtx = useStudioCtx();
  const vc = studioCtx.focusedViewCtx();
  const showSlotPlaceholder = studioCtx.showSlotPlaceholder();
  const showContainerPlaceholder = studioCtx.showContainerPlaceholder();
  const showMultiplayerSelections = studioCtx.showMultiplayerSelections();
  const showAncestorsHoverBoxes = studioCtx.showAncestorsHoverBoxes();

  return (
    <IFrameAwareDropdownMenu
      menu={() => {
        const builder = new MenuBuilder();
        builder.genSection(undefined, (push) => {
          push(
            <Menu.Item
              onClick={async () => studioCtx.toggleShowSlotPlaceholder()}
              key="toggle-show-slot-placeholder"
            >
              <Icon
                className="dimfg mr-sm"
                icon={
                  showSlotPlaceholder
                    ? HidePlaceholderIcon
                    : ShowPlaceholderIcon
                }
              />
              {t(
                showSlotPlaceholder
                  ? "Hide placeholders for empty slots"
                  : "Show placeholders for empty slots",
              )}
            </Menu.Item>,
          );
          push(
            <Menu.Item
              onClick={async () => studioCtx.toggleShowContainerPlaceholder()}
              key="toggle-show-container-placeholder"
            >
              <Icon
                className="dimfg mr-sm"
                icon={
                  showContainerPlaceholder
                    ? HidePlaceholderIcon
                    : ShowPlaceholderIcon
                }
              />
              {t(
                showContainerPlaceholder
                  ? "Hide placeholders for empty containers"
                  : "Show placeholders for empty containers",
              )}
            </Menu.Item>,
          );
          push(
            <Menu.Item
              onClick={async () => studioCtx.toggleShowMultiplayerSelections()}
              key="toggle-show-multiplayer"
            >
              <Icon
                className="dimfg mr-sm"
                icon={
                  showMultiplayerSelections
                    ? HidePlaceholderIcon
                    : ShowPlaceholderIcon
                }
              />
              {t(
                showMultiplayerSelections
                  ? "Hide cursors and selections from other users"
                  : "Show cursors and selections from other users",
              )}
            </Menu.Item>,
          );
          push(
            <Menu.Item
              onClick={async () => studioCtx.toggleShowAncestorsHoverBoxes()}
              key="toggle-show-ancestors-hover-boxes"
            >
              <Icon
                className="dimfg mr-sm"
                icon={
                  showSlotPlaceholder
                    ? HidePlaceholderIcon
                    : ShowPlaceholderIcon
                }
              />
              {t(
                showAncestorsHoverBoxes
                  ? "Hide container outlines when hovering"
                  : "Show container outlines when hovering",
              )}
            </Menu.Item>,
          );

          if (vc) {
            const isOutlineMode = vc.canvasCtx.isOutlineMode();
            push(
              <Menu.Item
                onClick={() =>
                  vc.canvasCtx.setOutlineMode(!vc.canvasCtx.isOutlineMode())
                }
                key="toggle-show-outline"
              >
                <TextAndShortcut shortcut={getComboForAction("OUTLINE_MODE")}>
                  {t(isOutlineMode ? "Hide outline mode" : "Show outline mode")}
                </TextAndShortcut>
              </Menu.Item>,
            );
          }

          const isFocusedMode = studioCtx.focusedMode;
          if (isFocusedMode || isDedicatedArena(studioCtx.currentArena)) {
            push(
              <Menu.Item
                onClick={async () =>
                  studioCtx.changeUnsafe(() => studioCtx.toggleFocusedMode())
                }
                key="toggle-focus-mode"
              >
                <TextAndShortcut
                  shortcut={getComboForAction("TOGGLE_FOCUSED_MODE")}
                >
                  {t(
                    isFocusedMode
                      ? "Turn on design mode"
                      : "Turn off design mode",
                  )}
                </TextAndShortcut>
              </Menu.Item>,
            );
          }

          const isAutoOpenMode = studioCtx.isAutoOpenMode;
          push(
            <Menu.Item
              onClick={() => studioCtx.toggleAutoOpenMode()}
              key="toggle-auto-open-mode"
            >
              {t(
                isAutoOpenMode
                  ? "Turn off auto-open mode"
                  : "Turn on auto-open mode",
              )}
            </Menu.Item>,
          );

          if (studioCtx.showComments()) {
            const showCommentsOverlay = studioCtx.showCommentsOverlay;
            push(
              <Menu.Item
                onClick={() => studioCtx.toggleShowCommentsOverlay()}
                key="toggle-show-comments-overlay"
              >
                {t(
                  showCommentsOverlay
                    ? "Hide comments overlay"
                    : "Show comments overlay",
                )}
              </Menu.Item>,
            );
          }

          const canChangeContentEditorMode =
            !studioCtx.isContentEditor() && !DEVFLAGS.contentEditorMode;
          if (canChangeContentEditorMode) {
            push(
              <Menu.Item
                onClick={async () =>
                  await studioCtx.change(() => {
                    studioCtx.toggleContentEditorMode();
                    return ok();
                  })
                }
                key="toggle-content-editor-mode"
              >
                <Tooltip zIndex={200000} title={contentCreatorModeHelp}>
                  {t(
                    studioCtx.contentEditorMode
                      ? "Turn off content creator mode"
                      : "Turn on content creator mode",
                  )}
                </Tooltip>
              </Menu.Item>,
            );
          }

          push(
            <Menu.Item
              onClick={async () => {
                await studioCtx.refreshFetchedDataFromPlasmicQuery();
                await studioCtx.refreshAppUserProperties();
              }}
              key="refresh-data"
            >
              <Icon className="dimfg mr-sm" icon={Refresh2SvgIcon} />
              {t("Refresh data")}
            </Menu.Item>,
          );
        });

        return builder.build({
          menuName: "view-menu",
        });
      }}
    >
      <PlasmicViewButton
        mode={props.mode}
        root={{
          props: {
            ...props,
            "aria-label": t("View"),
            id: "view-menu",
          },
        }}
      />
    </IFrameAwareDropdownMenu>
  );
});

export default ViewButton;
