import { useI18n } from "@/wab/client/i18n";
import { UiText } from "@/wab/client/i18n/UiText";
// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.

import {
  MenuBuilder,
  TextAndShortcut,
} from "@/wab/client/components/menu-builder";
import { useEditorPopupStyles } from "@/wab/client/components/ui/layout-styles";
import { IFrameAwareDropdownMenu } from "@/wab/client/components/widgets";
import { DefaultViewButtonProps } from "@/wab/client/plasmic/plasmic_kit_top_bar/PlasmicViewButton";
import { getComboForAction } from "@/wab/client/shortcuts/studio/studio-shortcuts";
import { useStudioCtx } from "@/wab/client/studio-ctx/StudioCtx";
import { isDedicatedArena } from "@/wab/shared/Arenas";
import { DEVFLAGS } from "@/wab/shared/devflags";
import {
  BorderOutlined,
  CommentOutlined,
  ControlOutlined,
  EditOutlined,
  EyeInvisibleOutlined,
  EyeOutlined,
  ReloadOutlined,
} from "@ant-design/icons";
import { Button, Menu, Tooltip } from "antd";
import { createStyles } from "antd-style";
import { observer } from "mobx-react";
import { ok } from "neverthrow";
import * as React from "react";

type ViewButtonProps = DefaultViewButtonProps;

const useStyles = createStyles(({ token }) => ({
  popup: {
    "& .ant-menu, & .ant-dropdown-menu": {
      width: 336,
      maxWidth: "calc(100vw - 32px)",
      padding: 6,
      background: token.colorBgElevated,
      border: `1px solid ${token.colorBorderSecondary}`,
      borderRadius: token.borderRadiusLG,
      boxShadow: token.boxShadowSecondary,
      color: token.colorText,
    },
    "& .ant-menu-item, & .ant-dropdown-menu-item": {
      height: 36,
      minHeight: 36,
      lineHeight: "20px",
      padding: "8px 10px",
      margin: "2px 0",
      width: "100%",
      borderRadius: token.borderRadius,
      fontSize: 13,
      color: token.colorText,
    },
    "& .ant-menu-title-content, & .ant-dropdown-menu-title-content": {
      display: "flex",
      alignItems: "center",
      gap: 10,
    },
    "& .ant-menu-title-content > .flex, & .ant-dropdown-menu-title-content > .flex":
      { flex: 1, minWidth: 0, alignItems: "center" },
    "& .anticon, & .dimfg": {
      width: 16,
      height: 16,
      fontSize: 16,
      flexShrink: 0,
      color: token.colorTextSecondary,
    },
    "& .mr-sm": { marginRight: 0 },
    "& .shortcut-combo": {
      background: token.colorFillTertiary,
      color: token.colorTextSecondary,
      fontSize: 11,
      lineHeight: "18px",
      padding: "0 5px",
      border: `1px solid ${token.colorBorderSecondary}`,
      borderRadius: 4,
      boxShadow: "none",
      marginLeft: 12,
    },
    "& .ant-menu-item-divider, & .ant-dropdown-menu-item-divider": {
      margin: "6px 4px",
      borderColor: token.colorBorderSecondary,
    },
    "& .ant-menu-item:hover, & .ant-dropdown-menu-item:hover": {
      background: token.colorFillSecondary,
    },
    "& .ant-menu-item:focus-visible, & .ant-dropdown-menu-item:focus-visible": {
      outline: `2px solid ${token.colorPrimary}`,
      outlineOffset: -2,
    },
  },
}));

const contentCreatorModeHelp = (
  <>
    <div>
      <UiText
        message={
          "Content creator mode simplifies the UI and limits edits to ensure design consistency."
        }
      />
    </div>
    <div className="mt-sm">
      <UiText
        message={
          "It limits insertion to existing components in this project and hides style settings and most design panels."
        }
      />
    </div>
    <div className="mt-sm">
      <UiText
        message={
          "Users with content creator roles always use content creator mode."
        }
      />
    </div>
  </>
);

const ViewButton = observer(function ViewButton(props: ViewButtonProps) {
  const { t } = useI18n();
  const { styles } = useStyles();
  const { styles: popupStyles } = useEditorPopupStyles();
  const studioCtx = useStudioCtx();
  const vc = studioCtx.focusedViewCtx();
  const showSlotPlaceholder = studioCtx.showSlotPlaceholder();
  const showContainerPlaceholder = studioCtx.showContainerPlaceholder();
  const showMultiplayerSelections = studioCtx.showMultiplayerSelections();
  const showAncestorsHoverBoxes = studioCtx.showAncestorsHoverBoxes();

  return (
    <IFrameAwareDropdownMenu
      overlayClassName={`${popupStyles.root} ${styles.popup}`}
      menu={() => {
        const builder = new MenuBuilder();
        builder.genSection(undefined, (push) => {
          push(
            <Menu.Item
              onClick={async () => studioCtx.toggleShowSlotPlaceholder()}
              key="toggle-show-slot-placeholder"
            >
              {showSlotPlaceholder ? <EyeInvisibleOutlined /> : <EyeOutlined />}
              {t(
                showSlotPlaceholder
                  ? "Hide placeholders for empty slots"
                  : "Show placeholders for empty slots",
              )}
            </Menu.Item>,
          );
          push(
            <Menu.Item
              onClick={async () => studioCtx.toggleShowContainerPlaceholder()}
              key="toggle-show-container-placeholder"
            >
              {showContainerPlaceholder ? (
                <EyeInvisibleOutlined />
              ) : (
                <EyeOutlined />
              )}
              {t(
                showContainerPlaceholder
                  ? "Hide placeholders for empty containers"
                  : "Show placeholders for empty containers",
              )}
            </Menu.Item>,
          );
          push(
            <Menu.Item
              onClick={async () => studioCtx.toggleShowMultiplayerSelections()}
              key="toggle-show-multiplayer"
            >
              {showMultiplayerSelections ? (
                <EyeInvisibleOutlined />
              ) : (
                <EyeOutlined />
              )}
              {t(
                showMultiplayerSelections
                  ? "Hide cursors and selections from other users"
                  : "Show cursors and selections from other users",
              )}
            </Menu.Item>,
          );
          push(
            <Menu.Item
              onClick={async () => studioCtx.toggleShowAncestorsHoverBoxes()}
              key="toggle-show-ancestors-hover-boxes"
            >
              {showAncestorsHoverBoxes ? (
                <EyeInvisibleOutlined />
              ) : (
                <EyeOutlined />
              )}
              {t(
                showAncestorsHoverBoxes
                  ? "Hide container outlines when hovering"
                  : "Show container outlines when hovering",
              )}
            </Menu.Item>,
          );

          if (vc) {
            const isOutlineMode = vc.canvasCtx.isOutlineMode();
            push(
              <Menu.Item
                onClick={() =>
                  vc.canvasCtx.setOutlineMode(!vc.canvasCtx.isOutlineMode())
                }
                key="toggle-show-outline"
              >
                <BorderOutlined />
                <TextAndShortcut shortcut={getComboForAction("OUTLINE_MODE")}>
                  {t(isOutlineMode ? "Hide outline mode" : "Show outline mode")}
                </TextAndShortcut>
              </Menu.Item>,
            );
          }
        });
        builder.genSection(undefined, (push) => {
          const isFocusedMode = studioCtx.focusedMode;
          if (isFocusedMode || isDedicatedArena(studioCtx.currentArena)) {
            push(
              <Menu.Item
                onClick={async () =>
                  studioCtx.changeUnsafe(() => studioCtx.toggleFocusedMode())
                }
                key="toggle-focus-mode"
              >
                <EditOutlined />
                <TextAndShortcut
                  shortcut={getComboForAction("TOGGLE_FOCUSED_MODE")}
                >
                  {t(
                    isFocusedMode
                      ? "Turn on design mode"
                      : "Turn off design mode",
                  )}
                </TextAndShortcut>
              </Menu.Item>,
            );
          }

          const isAutoOpenMode = studioCtx.isAutoOpenMode;
          push(
            <Menu.Item
              onClick={() => studioCtx.toggleAutoOpenMode()}
              key="toggle-auto-open-mode"
            >
              <ControlOutlined />
              {t(
                isAutoOpenMode
                  ? "Turn off auto-open mode"
                  : "Turn on auto-open mode",
              )}
            </Menu.Item>,
          );

          if (studioCtx.showComments()) {
            const showCommentsOverlay = studioCtx.showCommentsOverlay;
            push(
              <Menu.Item
                onClick={() => studioCtx.toggleShowCommentsOverlay()}
                key="toggle-show-comments-overlay"
              >
                <CommentOutlined />
                {t(
                  showCommentsOverlay
                    ? "Hide comments overlay"
                    : "Show comments overlay",
                )}
              </Menu.Item>,
            );
          }

          const canChangeContentEditorMode =
            !studioCtx.isContentEditor() && !DEVFLAGS.contentEditorMode;
          if (canChangeContentEditorMode) {
            push(
              <Menu.Item
                onClick={async () =>
                  await studioCtx.change(() => {
                    studioCtx.toggleContentEditorMode();
                    return ok();
                  })
                }
                key="toggle-content-editor-mode"
              >
                <EditOutlined />
                <Tooltip zIndex={200000} title={contentCreatorModeHelp}>
                  {t(
                    studioCtx.contentEditorMode
                      ? "Turn off content creator mode"
                      : "Turn on content creator mode",
                  )}
                </Tooltip>
              </Menu.Item>,
            );
          }
        });
        builder.genSection(undefined, (push) => {
          push(
            <Menu.Item
              onClick={async () => {
                await studioCtx.refreshFetchedDataFromPlasmicQuery();
                await studioCtx.refreshAppUserProperties();
              }}
              key="refresh-data"
            >
              <ReloadOutlined />
              {t("Refresh data")}
            </Menu.Item>,
          );
        });

        return builder.build({
          menuName: "view-menu",
        });
      }}
    >
      <Button type="text" aria-label={t("View")} id="view-menu">
        {t("View")}
        <svg
          viewBox="0 0 24 24"
          aria-hidden="true"
          className="editor-view-chevron"
        >
          <path d="M6 9l6 6 6-6" />
        </svg>
      </Button>
    </IFrameAwareDropdownMenu>
  );
});

export default ViewButton;
