// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import { reportError } from "@/wab/client/ErrorNotifications";
import CmsEntryItem from "@/wab/client/components/cms/CmsEntryItem";
import { useCmsLayoutStyles } from "@/wab/client/components/cms/CmsLayout.styles";
import {
  useCmsTable,
  useMutateTableRows,
} from "@/wab/client/components/cms/cms-contexts";
import { useApi } from "@/wab/client/contexts/AppContexts";
import { useI18n } from "@/wab/client/i18n";
import { DefaultCmsEntriesListProps } from "@/wab/client/plasmic/plasmic_kit_cms/PlasmicCmsEntriesList";
import { useHistory } from "@/wab/client/route/HistoryProvider";
import { useMatchedRoute } from "@/wab/client/route/useMatchedRoute";
import { ApiCmseRow, CmsDatabaseId, CmsTableId } from "@/wab/shared/ApiSchema";
import { ensure } from "@/wab/shared/common";
import { APP_ROUTES } from "@/wab/shared/route/app-routes";
import { naturalSort } from "@/wab/shared/sort";
import { PlusOutlined } from "@ant-design/icons";
import { HTMLElementRefOf } from "@plasmicapp/react-web";
import {
  Alert,
  Button,
  Empty,
  Flex,
  Input,
  Select,
  Skeleton,
  Typography,
} from "antd";
import fastStringify from "fast-stringify";
import { debounce } from "lodash";
import * as React from "react";

interface SortConfig {
  key: string;
  label:
    | "Last created"
    | "First created"
    | "Last updated"
    | "First updated"
    | "Identifier (A-Z)"
    | "Identifier (Z-A)";
  sortFn: (rows: ApiCmseRow[]) => ApiCmseRow[];
}

const LAST_CREATED_SORT: SortConfig = {
  key: "last-created",
  label: "Last created",
  sortFn: (rows) =>
    [...rows].sort(
      (a, b) =>
        new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime(),
    ),
};

const FIRST_CREATED_SORT: SortConfig = {
  key: "first-created",
  label: "First created",
  sortFn: (rows) =>
    [...rows].sort(
      (a, b) =>
        new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime(),
    ),
};

const LAST_UPDATED_SORT: SortConfig = {
  key: "last-updated",
  label: "Last updated",
  sortFn: (rows) =>
    [...rows].sort(
      (a, b) =>
        new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime(),
    ),
};

const FIRST_UPDATED_SORT: SortConfig = {
  key: "first-updated",
  label: "First updated",
  sortFn: (rows) =>
    [...rows].sort(
      (a, b) =>
        new Date(a.updatedAt).getTime() - new Date(b.updatedAt).getTime(),
    ),
};

const IDENTIFIER_A_Z_SORT: SortConfig = {
  key: "identifier-a-z",
  label: "Identifier (A-Z)",
  sortFn: (rows) => naturalSort(rows, (row) => row.identifier ?? ""),
};

const IDENTIFIER_Z_A_SORT: SortConfig = {
  key: "identifier-z-a",
  label: "Identifier (Z-A)",
  sortFn: (rows) => naturalSort(rows, (row) => row.identifier ?? "").reverse(),
};

const SORT_CONFIGS: SortConfig[] = [
  LAST_CREATED_SORT,
  FIRST_CREATED_SORT,
  LAST_UPDATED_SORT,
  FIRST_UPDATED_SORT,
  IDENTIFIER_A_Z_SORT,
  IDENTIFIER_Z_A_SORT,
];

export interface CmsEntriesListProps extends DefaultCmsEntriesListProps {
  rows?: ApiCmseRow[];
}

function CmsEntriesList_(
  props: CmsEntriesListProps,
  ref: HTMLElementRefOf<"div">,
) {
  const { rows, className } = props;
  const { t } = useI18n();
  const { styles, cx } = useCmsLayoutStyles();
  const [creating, setCreating] = React.useState(false);
  const [createError, setCreateError] = React.useState(false);
  const api = useApi();
  const history = useHistory();
  const match = ensure(
    useMatchedRoute<{
      databaseId: CmsDatabaseId;
      tableId: CmsTableId;
    }>(),
    "CmsEntriesList must be rendered within a matched route",
  );
  const { databaseId, tableId } = match.pathParams;
  const table = useCmsTable(databaseId, tableId);
  const mutateTableRows = useMutateTableRows();
  const [query, setQuery] = React.useState("");
  const [debouncedQuery, setDebouncedQuery] = React.useState("");
  const [sortConfig, setSortConfig] =
    React.useState<SortConfig>(LAST_CREATED_SORT);

  const sortedAndFilteredRows = React.useMemo(() => {
    if (!rows) {
      return [];
    }
    const hasQuery = !!debouncedQuery && debouncedQuery.trim().length > 0;
    const normQuery = debouncedQuery.toLowerCase();
    const filtered = hasQuery
      ? rows?.filter((row) =>
          fastStringify(Object.values(row)).toLowerCase().includes(normQuery),
        )
      : rows;

    return sortConfig.sortFn(filtered);
  }, [rows, debouncedQuery, sortConfig]);

  const debouncedSetQuery = React.useCallback(
    debounce((q: string) => {
      setDebouncedQuery(q);
    }, 300),
    [setDebouncedQuery],
  );

  React.useEffect(() => () => debouncedSetQuery.cancel(), [debouncedSetQuery]);

  if (!rows || !table) {
    return (
      <div
        className={cx(styles.entries, className)}
        role="status"
        aria-label={t("Loading content entries…")}
      >
        <Skeleton active />
      </div>
    );
  }

  const createEntry = async () => {
    setCreating(true);
    setCreateError(false);
    try {
      const row = await api.createCmsRow(tableId, {
        identifier: undefined,
        data: null,
        draftData: { "": {} },
      });
      await mutateTableRows(tableId).catch(reportError);
      history.push(
        APP_ROUTES.cmsEntry.fill({ databaseId, tableId, rowId: row.id }),
      );
    } catch {
      setCreateError(true);
    } finally {
      setCreating(false);
    }
  };

  return (
    <section ref={ref} className={cx(styles.entries, className)}>
      <Flex align="center" justify="space-between" gap={8}>
        <Typography.Text strong ellipsis>
          {table.name}
        </Typography.Text>
        <Button
          aria-label={t("Add new entry")}
          data-test-id="addEntryButton"
          icon={<PlusOutlined aria-hidden />}
          loading={creating}
          onClick={() => {
            void createEntry();
          }}
        />
      </Flex>
      <Input.Search
        aria-label={t("Search content entries")}
        placeholder={t("Search…")}
        value={query}
        allowClear
        onChange={(event) => {
          setQuery(event.target.value);
          debouncedSetQuery(event.target.value);
        }}
      />
      <Select
        aria-label={t("Sort by")}
        value={sortConfig.key}
        options={SORT_CONFIGS.map((config) => ({
          value: config.key,
          label: t(config.label),
        }))}
        onChange={(key) =>
          setSortConfig(
            ensure(
              SORT_CONFIGS.find((config) => config.key === key),
              "Unknown CMS sort option",
            ),
          )
        }
      />
      {createError && (
        <Alert
          type="error"
          showIcon
          title={t("Failed to create content entry")}
        />
      )}
      <div className={styles.entryList}>
        {sortedAndFilteredRows.length ? (
          sortedAndFilteredRows.map((row) => (
            <CmsEntryItem table={table} row={row} key={row.id} />
          ))
        ) : (
          <Empty
            image={Empty.PRESENTED_IMAGE_SIMPLE}
            description={
              debouncedQuery.trim()
                ? t("No matching content entries")
                : t("No content entries yet")
            }
          />
        )}
      </div>
    </section>
  );
}

const CmsEntriesList = React.forwardRef(CmsEntriesList_);
export default CmsEntriesList;
