import styles from "@/wab/client/components/dashboard/dashboard.module.scss";
import { useI18n } from "@/wab/client/i18n";
// This is a skeleton starter React component generated by Plasmic.
import { HTMLElementRefOf } from "@plasmicapp/react-web";
import uniqBy from "lodash/uniqBy";
// This file is owned by you, feel free to edit as you see fit.
import { documentTitle } from "@/wab/client/components/dashboard/page-utils";
import { Spinner } from "@/wab/client/components/widgets";
import { useAppCtx } from "@/wab/client/contexts/AppContexts";
import {
  useAsyncFnStrict,
  useAsyncStrict,
} from "@/wab/client/hooks/useAsyncStrict";
import { useProjectsFilter } from "@/wab/client/hooks/useProjectsFilter";
import {
  DefaultMyPlaygroundProps,
  PlasmicMyPlayground,
} from "@/wab/client/plasmic/plasmic_kit_dashboard/PlasmicMyPlayground";
import * as React from "react";

export type MyPlaygroundProps = DefaultMyPlaygroundProps;

function MyPlayground_(props: MyPlaygroundProps, ref: HTMLElementRefOf<"div">) {
  const { t } = useI18n();
  const appCtx = useAppCtx();

  const [asyncData, fetchAsyncData] = useAsyncFnStrict(async () => {
    const { workspace, perms: workspacePerms } =
      await appCtx.api.getPersonalWorkspace();
    const workspaceId = workspace.id;
    const { projects, perms: projectsPerms } = await appCtx.api.getProjects({
      query: "byWorkspace",
      workspaceId,
    });
    const databases =
      await appCtx.api.listCmsDatabasesForWorkspace(workspaceId);
    const perms = uniqBy([...workspacePerms, ...projectsPerms], (p) => p.id);
    return { workspace, projects, databases, perms };
  }, []);
  useAsyncStrict(fetchAsyncData, []);

  const {
    projects,
    databases,
    matcher,
    props: filterProps,
  } = useProjectsFilter(asyncData.value?.projects, asyncData.value?.databases);

  const data = asyncData.value;
  if (!data) {
    return (
      <>
        {documentTitle(t("My Playground"))}
        <Spinner />
      </>
    );
  }

  return (
    <>
      {documentTitle(t("My Playground"))}
      <PlasmicMyPlayground
        root={{ ref, className: styles.dashboardContent }}
        {...props}
        defaultLayout={{ render: ({ children }) => <>{children}</> }}
        workspaceSection={{
          props: {
            workspace: {
              ...data.workspace,
              name: t("My Playground"),
              description: t("My Playground"),
            },
            filterProps,
            databases,
            projects,
            perms: data.perms,
            matcher,
            onUpdate: async () => {
              await fetchAsyncData();
            },
          },
        }}
      />
    </>
  );
}

const MyPlayground = React.forwardRef(MyPlayground_);
export default MyPlayground;
