import { useI18n } from "@/wab/client/i18n";
// This is a skeleton starter React component generated by Plasmic.
// Feel free to edit as you see fit.
import { AppCtx } from "@/wab/client/app-ctx";
import HostUrlInput from "@/wab/client/components/HostUrlInput";
import { Modal } from "@/wab/client/components/widgets/Modal";
import React from "react";

interface HostConfigProps {
  appCtx: AppCtx;
  onCancel: () => void;
  onUpdate: () => void;
}

export function AddTrustedHostModal({
  appCtx,
  onCancel,
  onUpdate,
}: HostConfigProps) {
  const { t } = useI18n();
  return (
    <Modal
      title={t("Add trusted host")}
      visible
      onCancel={() => onCancel()}
      footer={null}
    >
      {t("Host your projects in your own app to use your own components.")}{" "}
      <br />
      <a href="https://www.plasmic.app/learn/app-hosting/" target="_blank">
        {t("Learn how to set up app hosting")}
      </a>
      .
      <HostUrlInput
        className="mv-xlg"
        originOnly
        onConfirm={async (_url, parsedUrl) => {
          await appCtx.api.addTrustedHost(parsedUrl.origin);
          onUpdate();
        }}
      />
      {t("Only add domains you trust.")}
    </Modal>
  );
}
