// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import {
  IFrameAwareDropdownMenu,
  MenuMaker,
} from "@/wab/client/components/widgets";
import IconButton from "@/wab/client/components/widgets/IconButton";
import DotsVerticalSvgIcon from "@/wab/client/plasmic/plasmic_kit_icons/icons/PlasmicIcon__DotsVerticalSvg";
import * as React from "react";

interface MenuButtonProps {
  menu?: React.ReactNode | MenuMaker;
  className?: string;
  style?: React.CSSProperties;
  onVisibleChange?: (visible: boolean) => void;
  onContextMenu?: (e: React.MouseEvent) => void;
  align?: React.ComponentProps<typeof IFrameAwareDropdownMenu>["align"];
  tabIndex?: number;
  "aria-label"?: string;
}

function MenuButton(props: MenuButtonProps) {
  const {
    menu,
    className,
    style,
    onVisibleChange,
    onContextMenu,
    align,
    ...extraProps
  } = props;
  if (!menu && !onContextMenu) {
    return null;
  }
  const button = (
    <IconButton
      aria-label={props["aria-label"] ?? "More actions"}
      size="vertical"
      onClick={(e: React.MouseEvent) => {
        e.preventDefault();
        e.stopPropagation();
        onContextMenu?.(e);
      }}
      className={className}
      style={style}
      {...extraProps}
    >
      <DotsVerticalSvgIcon />
    </IconButton>
  );
  return onContextMenu ? (
    button
  ) : (
    <IFrameAwareDropdownMenu
      menu={menu}
      onVisibleChange={onVisibleChange}
      align={align}
    >
      {button}
    </IFrameAwareDropdownMenu>
  );
}

export default MenuButton;
