import { useDocsLayoutStyles } from "@/wab/client/components/docs/DocsLayout.styles";
// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import { useDocsPortalCtx } from "@/wab/client/components/docs/DocsPortalCtx";
import {
  DefaultDocsPortalBranchesProps,
  PlasmicDocsPortalBranches,
} from "@/wab/client/plasmic/plasmic_kit_docs_portal/PlasmicDocsPortalBranches";
import { APP_ROUTES } from "@/wab/shared/route/app-routes";
import * as React from "react";

type DocsPortalBranchesProps = DefaultDocsPortalBranchesProps;

function DocsPortalBranches(props: DocsPortalBranchesProps) {
  const docsCtx = useDocsPortalCtx();
  const { styles } = useDocsLayoutStyles();
  const projectId = docsCtx.studioCtx.siteInfo.id;
  return (
    <PlasmicDocsPortalBranches
      {...props}
      docsPortalHeader={{ projectName: docsCtx.studioCtx.siteInfo.name }}
      codegenBranch={{
        destination: APP_ROUTES.projectDocsCodegenType.fill({
          projectId,
          codegenType: "codegen",
        }),
      }}
      loaderBranch={{
        destination: APP_ROUTES.projectDocsCodegenType.fill({
          projectId,
          codegenType: "loader",
        }),
      }}
      root={{
        className: styles.root,
        style: {
          position: "absolute",
          left: 0,
          right: 0,
          top: 0,
          bottom: 0,
        },
      }}
    />
  );
}

export default DocsPortalBranches;
