// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import { COMMANDS } from "@/wab/client/commands/command";
import { StringPropEditor } from "@/wab/client/components/sidebar-tabs/ComponentProps/StringPropEditor";
import { PropEditorRow } from "@/wab/client/components/sidebar-tabs/PropEditorRow";
import { LabeledItemRow } from "@/wab/client/components/sidebar/sidebar-helpers";
import StyleSelect from "@/wab/client/components/style-controls/StyleSelect";
import { validateStateAccessType } from "@/wab/client/operations/utils/validate-state-changes";
import {
  DefaultNewVariableProps,
  PlasmicNewVariable,
} from "@/wab/client/plasmic/plasmic_kit_state_management/PlasmicNewVariable";
import { StudioCtx } from "@/wab/client/studio-ctx/StudioCtx";
import { ViewCtx } from "@/wab/client/studio-ctx/view-ctx";
import { wabTypeToPropType } from "@/wab/shared/code-components/code-components";
import { assert, spawn } from "@/wab/shared/common";
import { isPageComponent } from "@/wab/shared/core/components";
import { codeLit, getRawCode, tryExtractString } from "@/wab/shared/core/exprs";
import {
  NORMAL_STATE_VARIABLE_TYPES,
  NormalStateVariableType,
  StateAccessType,
  isReadonlyState,
  getDefaultValueForStateVariableType,
} from "@/wab/shared/core/states";
import { evalCodeWithEnv } from "@/wab/shared/eval";
import {
  Component,
  Expr,
  State,
  isKnownTplSlot,
} from "@/wab/shared/model/classes";
import { convertVariableTypeToWabType } from "@/wab/shared/model/model-util";
import { HTMLElementRefOf } from "@plasmicapp/react-web";
import { Alert, notification } from "antd";
import { observer } from "mobx-react";
import * as React from "react";

export const PREVIEW_DISABLED_TOOLTIP_MESSAGE: Record<
  Exclude<StateAccessType, "private">,
  string
> = {
  writable:
    "For the read and write states, the initial value depends on the variant. Therefore, you should set them in the settings tab.",
  readonly: "It is not possible to update a read-only state.",
};

export interface VariableValueEditorProps {
  state: State;
  component: Component;
  studioCtx: StudioCtx;
  viewCtx: ViewCtx;
  disableInitialValue?: boolean;
  initialValueAbout?: string;
  onChangeInitialValue?: (expr: Expr | undefined) => void;
  hidePreview?: boolean;
}

export interface StateVariableDraft {
  name: string;
  variableType: NormalStateVariableType;
  accessType: StateAccessType;
  initialValue: Expr | null;
}

export interface NewVariableProps extends DefaultNewVariableProps {
  state: State;
  component: Component;
  studioCtx: StudioCtx;
  viewCtx: ViewCtx;
  mode?: "new" | "edit";
  onCancel?: () => void;
  onConfirm?: () => void;
  onDraftChange?: (changes: Partial<StateVariableDraft>) => void;
}

export const VariableValueEditor = observer(function VariableValueEditor({
  component,
  state,
  studioCtx,
  viewCtx,
  disableInitialValue = false,
  initialValueAbout,
  onChangeInitialValue,
  hidePreview = false,
}: VariableValueEditorProps) {
  assert(
    !isKnownTplSlot(component.tplTree),
    "slots can't be root of a component",
  );
  const [previewDraft, setPreviewDraft] = React.useState<Expr | undefined>(
    undefined,
  );
  const initialValue = hidePreview ? undefined : viewCtx.getStateCurrentInitialValue(state);
  const currentValue = hidePreview ? undefined : viewCtx.getCanvasStateValue(state);
  const hasTempValue = initialValue !== currentValue;
  const previewExpr = previewDraft ?? codeLit(currentValue);
  const propType = wabTypeToPropType(
    convertVariableTypeToWabType(state.variableType),
  );

  const env = viewCtx.getCanvasEnvForTpl(component.tplTree) ?? {};

  return (
    <div
      style={{ position: "relative", width: "100%" }}
      className={"flex-col flex-fill"}
    >
      <div className={"mb-m"}>
        <PropEditorRow
          viewCtx={viewCtx}
          tpl={component.tplTree}
          label={"初始值"}
          attr="initial-value"
          expr={state.param.defaultExpr ?? undefined}
          definedIndicator={{ source: "none" }}
          valueSetState={"isSet"}
          propType={propType}
          onChange={async (expr) => {
            const invalidMessage = validateStateAccessType(
              state.accessType,
              expr,
            );
            if (invalidMessage) {
              notification.error({
                message: "无法设置初始值",
                description: invalidMessage,
              });
              return;
            }
            if (onChangeInitialValue) {
              onChangeInitialValue(expr);
              return;
            }
            await COMMANDS.component.changeStateInitialValue.execute(
              studioCtx,
              { expr },
              { state },
            );
          }}
          layout={"vertical"}
          disableLinkToProp={true}
          about={initialValueAbout}
          disabled={disableInitialValue}
        />
      </div>
      {!hidePreview && !disableInitialValue && viewCtx.hasUnstableStateInitializer(state) && (
        <Alert
          className="mb-m"
          type="warning"
          showIcon
          message="初始值应保持稳定。随机数或当前时间请通过副作用设置。"
        />
      )}
      {!hidePreview && <PropEditorRow
        viewCtx={viewCtx}
        tpl={component.tplTree}
        label="预览值"
        attr="preview-value"
        about={
          state.implicitState && isReadonlyState(state.implicitState)
            ? PREVIEW_DISABLED_TOOLTIP_MESSAGE[state.implicitState.accessType]
            : "临时设置变量值，预览组件的外观和交互。"
        }
        disabled={
          state.implicitState ? isReadonlyState(state.implicitState) : false
        }
        expr={previewExpr}
        definedIndicator={
          hasTempValue && previewExpr
            ? {
                source: "setNonVariable",
                prop: "preview-value",
                value: tryExtractString(previewExpr) || "",
              }
            : { source: "none" }
        }
        valueSetState={"isSet"}
        propType={propType}
        onChange={(_expr) => {
          if (!_expr) {
            return;
          }
          setPreviewDraft(_expr);
          const code = getRawCode(_expr, {
            projectFlags: studioCtx.projectFlags(),
            component,
            inStudio: true,
          });
          const newValue = evalCodeWithEnv(code, env);
          viewCtx.setCanvasStateValue(state, newValue);
        }}
        onDelete={() => {
          setPreviewDraft(undefined);
          viewCtx.resetCanvasStateValue(state);
        }}
        layout={"vertical"}
        disableLinkToProp={true}
        disableDynamicValue={true}
      />}
    </div>
  );
});

const VariableEditingForm = observer(
  React.forwardRef(function VariableEditingForm(
    {
      component,
      state,
      studioCtx,
      viewCtx,
      mode = "edit",
      onCancel,
      onConfirm,
      onDraftChange,
      ...rest
    }: NewVariableProps,
    ref: HTMLElementRefOf<"div">,
  ) {
    const StringEditor = React.useCallback(
      ({
        label,
        onChange,
        value,
        "data-plasmic-prop": dataPlasmicProp,
      }: {
        label: React.ReactNode;
        onChange: (val: string) => void;
        value: string;
        "data-plasmic-prop"?: string;
      }) => (
        <LabeledItemRow layout={"vertical"} label={label}>
          <StringPropEditor
            onChange={onChange}
            value={value}
            valueSetState={"isSet"}
            disabled={false}
            data-plasmic-prop={dataPlasmicProp}
          />
        </LabeledItemRow>
      ),
      [],
    );

    const hasExternalAccess = state.accessType !== "private";
    return (
      <PlasmicNewVariable
        root={{ ref }}
        {...rest}
        variableName={
          <StringEditor
            label={state.implicitState ? "对外名称" : "名称"}
            onChange={(val) =>
              onDraftChange ? onDraftChange({ name: val }) : COMMANDS.component.changeStateVariableName.execute(
                studioCtx,
                {
                  varName: val,
                },
                {
                  state,
                  component,
                },
              )
            }
            data-plasmic-prop={"variable-name"}
            value={state.param.variable.name}
          />
        }
        variableType={{
          props: {
            value: state.variableType,
            "data-plasmic-prop": "variable-type",
            onChange: (val) =>
              onDraftChange ? val && onDraftChange({ variableType: val as NormalStateVariableType, initialValue: codeLit(getDefaultValueForStateVariableType(val as NormalStateVariableType)) }) : COMMANDS.component.changeStateVariableType.execute(
                studioCtx,
                {
                  type: val as NormalStateVariableType | null,
                },
                {
                  state,
                },
              ),
            children: NORMAL_STATE_VARIABLE_TYPES.map((stateType) => (
              <StyleSelect.Option value={stateType} key={stateType}>
                {{
                  text: "文本",
                  number: "数字",
                  boolean: "布尔值",
                  array: "数组",
                  object: "对象",
                  dateString: "日期字符串",
                  dateRangeStrings: "日期范围字符串",
                }[stateType]}
              </StyleSelect.Option>
            )),
          },
        }}
        isPageComponent={isPageComponent(component)}
        variableInitVal={
          <VariableValueEditor
            state={state}
            component={component}
            studioCtx={studioCtx}
            viewCtx={viewCtx}
            hidePreview={mode === "new"}
            onChangeInitialValue={onDraftChange ? (expr) => onDraftChange({ initialValue: expr ?? null }) : undefined}
          />
        }
        allowExternalAccess={{
          props: {
            isChecked: hasExternalAccess,
            onChange: (allow) => {
              if (onDraftChange) { onDraftChange({ accessType: allow ? "readonly" : "private" }); return; }
              spawn(
                COMMANDS.component.changeStateVariableAccessType.execute(
                  studioCtx,
                  {
                    accessType: allow ? "readonly" : "private",
                  },
                  {
                    state,
                  },
                ),
              );
            },
            "data-test-id": "allow-external-access",
          },
        }}
        isExternal={hasExternalAccess}
        accessTypeSelect={{
          props: {
            "data-plasmic-prop": "access-type",
            value: state.accessType,
            onChange: async (val) => {
              const invalidMessage = validateStateAccessType(
                val as StateAccessType,
                state.param.defaultExpr,
              );
              if (invalidMessage) {
                notification.error({
                  message: "无法设置访问类型",
                  description: invalidMessage,
                });
                return;
              }
              if (onDraftChange) { onDraftChange({ accessType: val as StateAccessType }); return; }
              await COMMANDS.component.changeStateVariableAccessType.execute(
                studioCtx,
                {
                  accessType: val as StateAccessType,
                },
                {
                  state,
                },
              );
            },
            children: (
              [
                {
                  value: "readonly",
                  label: "只读",
                },
                {
                  value: "writable",
                  label: "可读写",
                },
              ] as { value: StateAccessType; label: string }[]
            ).map(({ label, value }) => (
              <StyleSelect.Option value={value} key={value}>
                {label}
              </StyleSelect.Option>
            )),
          },
        }}
        accessType={
          state.accessType === "private"
            ? "_private"
            : (state.accessType as Exclude<StateAccessType, "private">)
        }
        isImplicitState={!!state.tplNode}
        withFormButtons={mode === "new"}
        cancelButton={{
          children: "取消",
          onClick: () => onCancel?.(),
        }}
        confirmButton={{
          props: {
            children: "确认",
            "data-test-id": "confirm",
            onClick: () => onConfirm?.(),
          },
        }}
      />
    );
  }),
);
export default VariableEditingForm;
