// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import {
  ChartFilters,
  useChartData,
} from "@/wab/client/components/analytics/useChartData";
import { getEventLabel } from "@/wab/client/components/analytics/utils";
import { useI18n } from "@/wab/client/i18n";
import { DefaultChartViewProps } from "@/wab/client/plasmic/plasmic_kit_analytics/PlasmicChartView";
import { ensure } from "@/wab/shared/common";
import { HTMLElementRefOf } from "@plasmicapp/react-web";
import { Alert, Button, Card, Empty, Skeleton, theme } from "antd";
import { sortBy, uniqBy } from "lodash";
import moment from "moment";
import * as React from "react";
import {
  Line,
  LineChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";

export interface ChartViewProps extends DefaultChartViewProps, ChartFilters {
  chartData: ReturnType<typeof useChartData>;
}

const CHART_MARGIN = {
  top: 20,
  bottom: 20,
  right: 50,
  left: 50,
};

function AnalyticsChartResult(
  props: ReturnType<typeof useChartData> & ChartFilters,
) {
  const { event, splitId, analyticsQuery, projectMeta } = props;
  const { token } = theme.useToken();
  const { t } = useI18n();

  if (!analyticsQuery || !projectMeta) {
    return null;
  }
  const analyticsData = analyticsQuery.data;

  const XAxisByTime = (
    <XAxis
      stroke={token.colorTextSecondary}
      dataKey={"time"}
      minTickGap={10}
      tickFormatter={(value) => {
        return moment.utc(value).format("MM-DD");
      }}
      label={{
        value: "",
        position: "bottom",
      }}
    />
  );

  const YAxisWithLabel = (
    <YAxis
      stroke={token.colorTextSecondary}
      label={{
        value: "",
        angle: -90,
        position: "left",
      }}
    />
  );

  const TooltipWithLabel = (
    <Tooltip
      contentStyle={{
        background: token.colorBgElevated,
        borderColor: token.colorBorder,
        color: token.colorText,
      }}
      labelStyle={{ color: token.colorText }}
      labelFormatter={(value) => {
        return moment.utc(value).format("MM-DD");
      }}
    />
  );

  if (Array.isArray(analyticsData)) {
    return (
      <ResponsiveContainer>
        <LineChart data={analyticsData} margin={CHART_MARGIN}>
          {XAxisByTime}
          {YAxisWithLabel}
          {TooltipWithLabel}
          <Line
            type="monotone"
            name={t(getEventLabel(event))}
            dataKey={event}
            stroke={token.colorPrimary}
            dot={false}
          />
        </LineChart>
      </ResponsiveContainer>
    );
  }

  ensure(splitId, "SplitId shouldn't be null for ChartView");

  const split = projectMeta.splits.find((s) => s.id === splitId);
  const sliceOriginal = ensure(
    split?.slices[0].id,
    "SplitSliceId shouldn't be null for ChartView",
  );
  const sliceOverride = ensure(
    split?.slices[1].id,
    "SplitSliceId shouldn't be null for ChartView",
  );
  const originalData = analyticsData[sliceOriginal];
  const overrideData = analyticsData[sliceOverride];

  return (
    <ResponsiveContainer>
      <LineChart
        data={sortBy(
          uniqBy([...(originalData ?? []), ...(overrideData ?? [])], "time"),
          "time",
        )}
        margin={CHART_MARGIN}
      >
        {XAxisByTime}
        {YAxisWithLabel}
        {TooltipWithLabel}
        <Line
          type="monotone"
          name={`${t("Original")} ${t(getEventLabel(event))}`}
          dataKey={({ time }) => {
            if (!originalData) {
              return 0;
            }
            const elem = (originalData as any[]).find((e) => e.time === time);
            return elem?.[event] ?? null;
          }}
          dot={false}
          stroke={token.colorPrimary}
        />
        <Line
          type="monotone"
          name={`${t("Override")} ${t(getEventLabel(event))}`}
          dataKey={({ time }) => {
            if (!overrideData) {
              return 0;
            }
            const elem = (overrideData as any[]).find((e) => e.time === time);
            return elem?.[event] ?? null;
          }}
          dot={false}
          stroke={token.colorSuccess}
        />
      </LineChart>
    </ResponsiveContainer>
  );
}

function ChartView_(props: ChartViewProps, ref: HTMLElementRefOf<"div">) {
  const {
    teamId,
    workspaceId,
    projectId,
    componentId,
    splitId,
    timeRange,
    event,
    period,
    chartData,
    ...rest
  } = props;

  const { t } = useI18n();
  return (
    <div ref={ref} className={rest.className} style={{ minWidth: 0 }}>
      <Card>
        {chartData.error ? (
          <Alert
            type="error"
            showIcon
            title={t("Failed to load analytics")}
            action={
              <Button
                onClick={() => {
                  void chartData.retry();
                }}
              >
                {t("Retry")}
              </Button>
            }
          />
        ) : chartData.isLoading ? (
          <div role="status" aria-label={t("Loading analytics…")}>
            <Skeleton active paragraph={{ rows: 6 }} />
          </div>
        ) : chartData.paywall ? (
          <Empty description={t("Analytics requires an upgraded plan")} />
        ) : chartData.isEmpty ? (
          <Empty description={t("No analytics data for these filters")} />
        ) : (
          <div style={{ height: 360, minWidth: 0 }}>
            <AnalyticsChartResult
              event={event}
              teamId={teamId}
              projectId={projectId}
              componentId={componentId}
              splitId={splitId}
              timeRange={timeRange}
              period={period}
              {...chartData}
            />
          </div>
        )}
      </Card>
    </div>
  );
}

const ChartView = React.forwardRef(ChartView_);
export default ChartView;
