// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import SharePageModal from "@/wab/client/components/analytics/SharePageModal";
import { useChartData } from "@/wab/client/components/analytics/useChartData";
import {
  ANALYTICS_EVENTS,
  formatChartData,
  getChartHeaders,
} from "@/wab/client/components/analytics/utils";
import { Modal } from "@/wab/client/components/widgets/Modal";
import { useI18n } from "@/wab/client/i18n";
import { DefaultDataFiltersProps } from "@/wab/client/plasmic/plasmic_kit_analytics/PlasmicDataFilters";
import { HTMLElementRefOf } from "@plasmicapp/react-web";
import { Button, DatePicker, Flex, Select, Typography } from "antd";
import dayjs, { Dayjs } from "dayjs";
import * as React from "react";
import { CSVLink } from "react-csv";

type TimeRange = [Dayjs | null, Dayjs | null];
export interface DataFiltersProps extends DefaultDataFiltersProps {
  projectId?: string;
  timeRange: TimeRange;
  event: string;
  period: string;
  chartData: ReturnType<typeof useChartData>;
  setTimeRange: (_: TimeRange) => void;
  setEvent: (_: string) => void;
  setPeriod: (_: string) => void;
}

function DataFilters_(props: DataFiltersProps, ref: HTMLElementRefOf<"div">) {
  const { t: uiT } = useI18n();
  const {
    timeRange,
    setTimeRange,
    event,
    setEvent,
    period,
    setPeriod,
    projectId,
    chartData,
    ...rest
  } = props;
  const [isModalVisible, setIsModalVisible] = React.useState(false);
  return (
    <>
      <Modal
        open={isModalVisible}
        onCancel={() => setIsModalVisible(false)}
        footer={null}
      >
        <SharePageModal />
      </Modal>
      <Flex ref={ref} className={rest.className} gap={16} wrap align="end">
        <Flex vertical gap={4} style={{ minWidth: 0, maxWidth: "100%" }}>
          <Typography.Text>{uiT("Time Range")}</Typography.Text>
          <DatePicker.RangePicker
            style={{ maxWidth: "100%" }}
            aria-label={uiT("Time Range")}
            value={timeRange}
            allowClear={false}
            presets={[
              {
                label: uiT("Last week"),
                value: () => [dayjs().subtract(1, "week"), dayjs()],
              },
              {
                label: uiT("Last month"),
                value: () => [dayjs().subtract(1, "month"), dayjs()],
              },
            ]}
            onChange={(values) => {
              if (values) {
                setTimeRange(values);
              }
            }}
            disabledDate={(date) => dayjs(date).isAfter(dayjs().endOf("day"))}
          />
        </Flex>
        <Flex vertical gap={4} style={{ minWidth: 160 }}>
          <Typography.Text>{uiT("Metric")}</Typography.Text>
          <Select
            aria-label={uiT("Metric")}
            value={event}
            onChange={setEvent}
            options={ANALYTICS_EVENTS.filter(
              (item) => projectId || item.value.includes("impressions"),
            ).map((item) => ({ ...item, label: uiT(item.label) }))}
          />
        </Flex>
        <Flex vertical gap={4} style={{ minWidth: 140 }}>
          <Typography.Text>{uiT("Period")}</Typography.Text>
          <Select
            aria-label={uiT("Period")}
            value={period}
            onChange={setPeriod}
            options={[
              { value: "day", label: uiT("Daily") },
              { value: "month", label: uiT("Monthly") },
            ]}
          />
        </Flex>
        <Button onClick={() => setIsModalVisible(true)}>{uiT("Share")}</Button>
        {chartData.error ||
        chartData.isLoading ||
        chartData.isEmpty ||
        chartData.paywall ? (
          <Button disabled>{uiT("Export CSV")}</Button>
        ) : (
          <CSVLink
            data={formatChartData(chartData)}
            headers={getChartHeaders(chartData)}
            filename="plasmic-analytics.csv"
          >
            <Button>{uiT("Export CSV")}</Button>
          </CSVLink>
        )}
      </Flex>
    </>
  );
}

const DataFilters = React.forwardRef(DataFilters_);
export default DataFilters;
