// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import {
  useProjectAnalyticsMeta,
  useTeamProjects,
} from "@/wab/client/components/analytics/analytics-contexts";
import { COMPONENT_PICKER_INFO } from "@/wab/client/components/analytics/utils";
import { useI18n } from "@/wab/client/i18n";
import { DefaultTeamFiltersProps } from "@/wab/client/plasmic/plasmic_kit_analytics/PlasmicTeamFilters";
import { HTMLElementRefOf } from "@plasmicapp/react-web";
import { Alert, Button, Flex, Select, Typography } from "antd";
import { groupBy } from "lodash";
import * as React from "react";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface TeamFiltersProps extends Omit<DefaultTeamFiltersProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultTeamFiltersProps altogether and have
// total control over the props for your component.
export interface TeamFiltersProps extends DefaultTeamFiltersProps {
  teamId: string;
  workspaceId?: string;
  projectId?: string;
  componentId?: string;
  splitId?: string;
  setWorkspaceId: (_?: string) => void;
  setProjectId: (_?: string) => void;
  setComponentId: (_?: string) => void;
  setSplitId: (_?: string) => void;
}

function TeamFilters_(props: TeamFiltersProps, ref: HTMLElementRefOf<"div">) {
  const { t: uiT } = useI18n();
  const {
    teamId,
    workspaceId,
    projectId,
    componentId,
    splitId,
    setWorkspaceId,
    setProjectId,
    setComponentId,
    setSplitId,
    ...rest
  } = props;

  const projects = useTeamProjects(teamId);
  const metadata = useProjectAnalyticsMeta(teamId, projectId);
  const projectMeta = metadata.data ?? { pages: [], splits: [] };
  const error = projects.error || metadata.error;
  return (
    <Flex ref={ref} vertical gap={12} className={rest.className}>
      {error && (
        <Alert
          type="error"
          showIcon
          title={uiT("Failed to load analytics filters")}
          action={
            <Button
              onClick={() => {
                void projects.mutate();
                void metadata.mutate();
              }}
            >
              {uiT("Retry")}
            </Button>
          }
        />
      )}
      <Flex gap={16} wrap>
        <Flex vertical gap={4} style={{ minWidth: 180, flex: 1 }}>
          <Typography.Text>{uiT("Project")}</Typography.Text>
          <Select
            aria-label={uiT("Project")}
            allowClear
            loading={projects.isLoading}
            value={projectId}
            placeholder={uiT("All projects")}
            onChange={(value) => setProjectId(value)}
            options={Object.values(
              groupBy(
                projects.data ?? [],
                (project) => project.workspaceId ?? "",
              ),
            ).map((group) => ({
              label: group[0].workspaceName ?? uiT("Other projects"),
              options: group.map((project) => ({
                label: project.name,
                value: project.id,
              })),
            }))}
          />
        </Flex>
        <Flex vertical gap={4} style={{ minWidth: 180, flex: 1 }}>
          <Typography.Text>{uiT("Page / component")}</Typography.Text>
          <Select
            aria-label={uiT("Page / component")}
            title={COMPONENT_PICKER_INFO}
            allowClear
            disabled={!projectId}
            loading={metadata.isLoading}
            value={componentId}
            placeholder={uiT("All pages and components")}
            onChange={(value) => setComponentId(value)}
            options={projectMeta.pages.map((page) => ({
              label: page.name,
              value: page.id,
            }))}
          />
        </Flex>
        <Flex vertical gap={4} style={{ minWidth: 180, flex: 1 }}>
          <Typography.Text>{uiT("Optimization")}</Typography.Text>
          <Select
            aria-label={uiT("Optimization")}
            allowClear
            disabled={!projectId}
            loading={metadata.isLoading}
            value={splitId}
            placeholder={uiT("All optimizations")}
            onChange={(value) => setSplitId(value)}
            options={projectMeta.splits.map((split) => ({
              label: split.name,
              value: split.id,
            }))}
          />
        </Flex>
      </Flex>
    </Flex>
  );
}

const TeamFilters = React.forwardRef(TeamFilters_);
export default TeamFilters;
